kibot:
  version: 1
  sch: Stylophon_1.kicad_sch
  pcb: Stylophon_1.kicad_pcb
  pro: Stylophon_1.kicad_pro  # Wichtig für KiCad 10!

outputs:
  - name: 'Schaltplan_PDF'
    type: pdf_schematic
    dir: cam
  - name: 'Platine_PNG'
    type: png
    dir: cam
  - name: '3D_Ansicht'
    type: step
    dir: cam